# Generated by Django 4.2.16 on 2024-11-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0055_auto_20241114_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLink',
        ),
    ]
