# Generated by Django 4.2.16 on 2024-11-20 18:37

from django.db import migrations

FLAG_NAME = "bulk-organization-user-creation"

def create_bulk_organization_user_creation_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flag = Flag(
        name=FLAG_NAME,
        testing=True
    )
    flag.save()

def delete_bulk_organization_user_creation_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flags = Flag.objects.filter(name=FLAG_NAME)
    flags.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0056_delete_historicallink'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]
    
    operations = [
        migrations.RunPython(create_bulk_organization_user_creation_feature_flag, delete_bulk_organization_user_creation_feature_flag),
    ]
